### ISSUE TITLE
Small feature request: Improve log output

### ISSUE THREAD

**Issue by halirutan** [ChrisCarini/intellij-platform-plugin-verifier-action#10]
If you have too much time on your hands, here are some small things that would improve the readability of the action's log drastically:

1. Use some _quiet_ option for the `curl` call to download the IDE zips. I'm not sure how other users feel, but when I scroll through the log to find the verifier output, the download progress of the zips is of no interest and just takes vertical space
2. Would it be possible to have "closable sections" for each step that can be opened like in the checkout action?
![image](https://user-images.githubusercontent.com/511683/95930548-0779ae00-0dc7-11eb-9176-3d12dffedc15.png)
With this, the verifier log would be extremely easy to read if one had sections _Initialization_, _Verification against IUXXX_, _Verification against ICXXX_, ... Right now, that's kind of hard to read
3. Have you tried which error message you get when you verify against an IDE that does not exist like `ideaIC:200`? I remember the error message was coming from `unzip` which could not unpack an unknown format. If possible, it would be better to give something clear like "could not download ..."

**Comment by ChrisCarini** [comment]
Hi @halirutan - these 3 are all great feedback / improvements! I might not have time to pick them all up right away, but I'll try to knock these out the next time I have a large-ish block of time to make the necessary changes! (I'm also open to PRs, if you have any interest in giving a stab at them yourself!)

Thank you for raising this issue!

**Comment by ChrisCarini** [comment]
Hi @halirutan - I guess I ended up having too much time on my hands ;)

Regarding your 3 requests above:

1. Just created PR #14 for silencing `curl` except for errors
2. Just created PR #14 for grouping the logs together
3. This should be tackled by the second part of PR #13 

Please take a look at both PR #13 and #14 when you have a chance and let me know what you think! (Both PRs have screenshots, so you should get an idea from those)

**Comment by ChrisCarini** [comment]
@halirutan - I haven't heard back from you in almost a month; I'm going to assume you are ok with the proposed change in the PR and merge this in.

**Comment by ChrisCarini** [comment]
@all-contributors please add @halirutan for bug, idea
