### ISSUE TITLE
[Question] Should comparability problems cause failures? 

### ISSUE THREAD

**Issue by Unthrottled** [ChrisCarini/intellij-platform-plugin-verifier-action#16]
I would have expected if there where compatibility issues with a plugin against a specific IDE version that the action would exit unsuccessfully, is that not the intended behavior? Is this an issue with the verifier itself?

[Action run in question](https://github.com/doki-theme/doki-theme-jetbrains/runs/2250264445?check_suite_focus=true)

```
Compatibility problems (2): 
    #Access to unresolved class com.intellij.util.ui.JBUI.CurrentTheme.Link.Foreground
        Method io.unthrottled.doki.settings.ThemeSettingsUI.createUIComponents() : void references an unresolved class com.intellij.util.ui.JBUI.CurrentTheme.Link.Foreground. This can lead to **NoSuchClassError** exception at runtime.
    #Invocation of unresolved method java.util.Optional.isEmpty() : boolean
        Method io.unthrottled.doki.stickers.EditorBackgroundWallpaperService.installEditorBackgroundImage$2.invoke() : void contains an *invokevirtual* instruction referencing an unresolved method java.util.Optional.isEmpty() : boolean. This can lead to **NoSuchMethodError** exception at runtime.
```

**Comment by ChrisCarini** [comment]
Hi @Unthrottled ! Can you try upgrading the GitHub action to the latest version (`1.0.5`) and re-run the workflow? It looks like you are using an older version of the action (`1.0.3`) and the recent versions have added logic to detect other failures (and, should allow for some configuration of the failures as well).

**Comment by Unthrottled** [comment]
Upgrading it did the trick! Thanks for the quick response and the handy action!
I've added a dependabot dependency upgrade config for action so I get the latest in the future.

**Comment by ChrisCarini** [comment]
Awesome, then you for confirming! And you're welcome! Glad you are using it and enjoying it!

I was going to suggest the dependabot integration, actually! :)

Have a great day!

**Comment by ChrisCarini** [comment]
@all-contributors please add @Unthrottled for bug
