### ISSUE TITLE
Retag @latest to point to @v1.0.5

### ISSUE THREAD

**Issue by takanuva15** [ChrisCarini/intellij-platform-plugin-verifier-action#18]
Currently the latest tag is pointing to an older release of this action. Can we please move it to point to v1.0.5?
(I tried using the "failure_levels" property and it failed saying unknown property since the latest version is apparently not the latest lol)

**Comment by ChrisCarini** [comment]
Hi @takanuva15 - thank you for bringing this to my attention! I have just updated the tags:
![Screen Shot 2021-05-08 at 14 20 14](https://user-images.githubusercontent.com/6374067/117553831-94f14980-b008-11eb-9187-98ef913cd07e.png)

I'm going to close this issue out, but please re-open/comment if you are still seeing undesired behavior.

**Comment by ChrisCarini** [comment]
@all-contributors please add @takanuva15 for bug, infra, maintenance

**Comment by takanuva15** [comment]
Dang 2 years in the making - that's elephant-grade memory. I'd forgotten about this within 30 days of posting xD
