### ISSUE TITLE
Plugin Verifier has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by sadv1r** [ChrisCarini/intellij-platform-plugin-verifier-action#21]
**Describe the bug**
Recently started to get this error:
`Error: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jetbrains/pluginverifier/PluginVerifierMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

I think this is because of [this commit in Verifier](https://github.com/JetBrains/intellij-plugin-verifier/commit/e2ddb60fc83a9bb404d7545642da1d2cf4d30f71)

**To Reproduce**
1. Run verification of plugin without changing default verifier version

**Expected behavior**
As always

**Desktop (please complete the following information):**
 - [GitHub Action](https://github.com/sadv1r/ansible-vault-editor-idea-plugin/runs/3035462494?check_suite_focus=true)

**Comment by ChrisCarini** [comment]
Thanks for reporting this issue, and also opening PR #22 to address this, @sadv1r ! 

I left a few comments on the PR.

**Comment by ChrisCarini** [comment]
Thank you again, @sadv1r , for reporting the issue and addressing it in PR #22. I have [released version `v1.0.7` which includes your PR change](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/releases/tag/v1.0.7). I will go ahead and close this issue out now. Please feel free to confirm this works as expected, and re-open if it does not - I am sure it will based on your testing! :) 🎉

**Comment by sadv1r** [comment]
Works as expected, thanks! https://github.com/sadv1r/ansible-vault-editor-idea-plugin/runs/3041786884?check_suite_focus=true

**Comment by ChrisCarini** [comment]
@all-contributors please add @sadv1r for userTesting
