### ISSUE TITLE
False positive from action when verifier jar fails to execute (eg jar upgrade to Java 11)

### ISSUE THREAD

**Issue by takanuva15** [ChrisCarini/intellij-platform-plugin-verifier-action#23]
**Describe the bug**
When running the action in my PR, it returns a success result even though the jar file was never actually executed due to an incompatible binary error due to the verifier jar's recent upgrade to Java 11.

**To Reproduce**
1. Run the action using the tag `ChrisCarini/intellij-platform-plugin-verifier-action@latest` and any IDE version.

**Expected behavior**
The github action should fail since the jar file was never executed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/6986426/128619328-03c4c377-c20a-4955-a730-f2d4aa395dbf.png)

```
Running verification on /github/workspace/*.zip for /github/home/ides/ideaIC-2020.1 /github/home/ides/ideaIC-2021.1 /github/home/ides/ideaIC-LATEST-EAP-SNAPSHOT /github/home/ides/pycharmPC-2020.1 /github/home/ides/pycharmPC-2021.1 /github/home/ides/pycharmPC-LATEST-EAP-SNAPSHOT...
  ##[debug]RUNNING COMMAND: java -jar "/github/home/verifier-cli-1.266-all.jar" check-plugin /github/workspace/*.zip /github/home/ides/ideaIC-2020.1 /github/home/ides/ideaIC-2021.1 /github/home/ides/ideaIC-LATEST-EAP-SNAPSHOT /github/home/ides/pycharmPC-2020.1 /github/home/ides/pycharmPC-2021.1 /github/home/ides/pycharmPC-LATEST-EAP-SNAPSHOT
  Error: A JNI error has occurred, please check your installation and try again
  Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jetbrains/pluginverifier/PluginVerifierMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
  	at java.lang.ClassLoader.defineClass1(Native Method)
  	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
  ::endgroup::
::set-output name=verification-output-log-filename::verification_result.log
##[debug]steps['verify']['outputs']['verification-output-log-filename']='verification_result.log'
::group::Running validations against output...
Running validations against output...
  ##[debug]
  Checking for the presence of [Compatibility warnings] in the verifier output...
...
```

**Desktop (please complete the following information):**
 - OS: GitHub action - OS is whatever the dockerfile is using

**Additional context**
There is 2 problems here:
1. The action should immediately fail if the execution of the jar results in exit code 1 (ie any exception).
2. The dockerfile needs to be updated to use a base image with java 11

## EDIT:
Ok so actually I see that the dockerfile was updated recently to java 11, so point #2 above is nulled. However, I can see that the "latest" tag is not actually pointing to the new v1.0.7 made recently, which would be the source of the issue. The v1.0.7 also seems to fix Point #2 above, so it's just a matter of updating the latest tag to point to v1.0.7 to resolve both issues

**Comment by ChrisCarini** [comment]
Hi @takanuva15 - My apologies! I have just updated the tag:
```
$ > git tag -d latest && git push origin :refs/tags/latest && git tag latest 6e5251ec2184504f627b69fcf80e45bc8ffab5b0 && git push origin latest
Deleted tag 'latest' (was 4a99296)
To github.com:ChrisCarini/intellij-platform-plugin-verifier-action.git
 - [deleted]         latest
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:ChrisCarini/intellij-platform-plugin-verifier-action.git
 * [new tag]         latest -> latest
```

And the `latest` tag now points to the correct commit:
![Screen Shot 2021-08-11 at 23 02 39](https://user-images.githubusercontent.com/6374067/129146003-88149ff8-2035-4b28-b433-96e6ff587bf9.png)

Thank you for reporting this! Please confirm this fixes the two issues you observed, if so, feel free to close out this issue!

**Comment by takanuva15** [comment]
Yep, updated tag fixed the issues

**Comment by ChrisCarini** [comment]
Great! Thank you, again, for reporting the issue and confirming it is fixed.
