### ISSUE TITLE
Cannot iterate over null (null)

### ISSUE THREAD

**Issue by glex85** [ChrisCarini/intellij-platform-plugin-verifier-action#25]
# Description
When I try to check compatibility with Github action, I faced below issue.
Please check this out.

**Error Output**
/usr/bin/docker run --name cf4eaa3aeb6624d2134085bb2430a5f0dafdb0_d2a56a --label cf4eaa --workdir /github/workspace --rm -e JAVA_HOME_8.0.312_x64 -e JAVA_HOME -e JAVA_HOME_8_0_312_X64 -e INPUT_IDE-VERSIONS -e INPUT_VERIFIER-VERSION -e INPUT_PLUGIN-LOCATION -e INPUT_FAILURE-LEVELS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -e CI=true --network github_network_e4461e3a7ae94c8faea51f3b2692117f -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/github/actions-runner/_work/_temp/_github_home":"/github/home" -v "/home/github/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/home/github/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/github/actions-runner/_work/sherlock-studio-plugin-gradle/sherlock-studio-plugin-gradle":"/github/workspace" cf4eaa:3aeb6624d2134085bb2430a5f0dafdb0  "LATEST" "build/distributions/*.zip" "ideaIC:2018.3.6
ideaIU:2018.3.6
ideaIC:2019.1.4
ideaIU:2019.1.4
ideaIC:2020.1.4
ideaIU:2020.1.4
ideaIC:2021.1.3
ideaIU:2021.1.3
" "COMPATIBILITY_PROBLEMS INVALID_PLUGIN"
Initializing...
  jq: error (at <stdin>:1): Cannot iterate over null (null)
  Error: =======================================================
  Error: ===-------------------------------------------------===
  Error: === An unexpected error occurred. Status code [5].
  Error: ===
  Error: === Please consider opening a bug for the developer:
  Error: ===    - Bug URL: https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/issues/new
  Error: ===    - Status Code: 5
  Error: ===-------------------------------------------------===
  Error: =======================================================

**Comment by glex85** [comment]
@ChrisCarini Yes, It is. Now It has same issue again :(

**Comment by glex85** [comment]
Thank you for your review.

**Comment by ChrisCarini** [comment]
@all-contributors please add @glex85 for bug, userTesting
