### ISSUE TITLE
entrypoint.sh has a bug

### ISSUE THREAD

**Issue by glex85** [ChrisCarini/intellij-platform-plugin-verifier-action#26]
VERIFIER_JAR_FILENAME should be declared before set VERIFIER_DOWNLOAD_URL.

**Current Code**
> VERIFIER_VERSION=${INPUT_VERIFIER_VERSION}
> VERIFIER_DOWNLOAD_URL="https://dl.bintray.com/jetbrains/intellij-plugin-service/org/jetbrains/intellij/plugins/verifier-cli/$INPUT_VERIFIER_VERSION/$VERIFIER_JAR_FILENAME"
> VERIFIER_JAR_FILENAME="verifier-cli-$VERIFIER_VERSION-all.jar"

**Comment by ChrisCarini** [comment]
Thank you for reporting this, @glex85 !
