### ISSUE TITLE
Unknown Failure Identified!

### ISSUE THREAD

**Issue by MemoryZy** [ChrisCarini/intellij-platform-plugin-verifier-action#73]
# Description
While running validations, I received an exception during the "Running validations against output..." step. I'm not sure what the error message is indicating.

# Information
**Plugin Name: ZhiYouToolkit**
**GitHub Repo URL: https://github.com/MemoryZy/ZhiYouToolkit**
**GitHub Action: https://github.com/MemoryZy/ZhiYouToolkit/blob/main/.github/workflows/Compatibility.yml**
**Failed GitHub Action Run Link: https://github.com/MemoryZy/ZhiYouToolkit/actions/runs/9263746476/job/25482703614**
**Error Output:**
```
Running validations against output...
  Checking for the presence of [Compatibility warnings] in the verifier output...
  Checking for the presence of [^Plugin (.*) against .*: .* compatibility problems?] in the verifier output...
  Checking for the presence of [Compatibility problems] in the verifier output...
  Checking for the presence of [Deprecated API usages] in the verifier output...
  [Deprecated API usages] was found in the verifier output. Failing check.
Error: ==============================================
Error: ==============================================
Error: ===                                        ===
Error: ===    PLUGIN FAILED VERIFICATION CHECK    ===
Error: ===                                        ===
Error: ==============================================
Error: ==============================================
Error: Exiting due to a known, handled, plugin validation failure.
```

![图片](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/assets/64096987/9662b4ce-4c19-41e1-b4df-f2c1a92d8d3b)

**Comment by ChrisCarini** [comment]
Hi @MemoryZy -

First off, thank you for using this action and opening an issue.

It looks like the verifier failed because of the below error:

> [Deprecated API usages] was found in the verifier output. Failing check.

You will either have to fix these deprecated errors, or disable these from being marked as errors. 

Best, 
Chris

**Comment by MemoryZy** [comment]
Yes, the program executed successfully after removing the `DEPRECATED_API_USAGES` option. Thank you.

**Comment by ChrisCarini** [comment]
Sounds good - I will close out this issue. Thank you again!
